spring:
  application:
    name: example-subscription-consumer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}

management:
    context-path: /internal

service:
  encryption:
    password: example
    salt: example

exampleservice:
  subscription-channel-name: synapse-example-subscriptions
  product-channel-name: synapse-example-subscribable-products
  subscribed-products-channel-name: synapse-example-subscribed-products

logging:
    config: classpath:logback-console.xml

server:
  port: 5556